version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${user}
      MONGO_INITDB_ROOT_PASSWORD: ${password}
      MONGO_INITDB_DATABASE: ${initdb}
      DB_NAME: ${db_name}
      DB_USER: ${db_user}
      DB_PASSWORD: ${db_password}
    volumes:
      - ./data-directory:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    ports:
      - "27017:27017"
    networks:
      - mnet
            
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${user}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${password}
      ME_CONFIG_MONGODB_URL: mongodb://${user}:${password}@mongo:27017/
    networks:
      - mnet
    ports:
      - 8081:8081
    depends_on:
      - mongo
    restart: unless-stopped

networks:
  mnet:
    driver: bridge